#include "stm32f4xx_hal.h"


/* Bootloader configuration */

#define BOOT_STATE_MAGIC     0xB007B007u
#define CONFIG_FLASH_ADDRESS 0x08010000u
#define CONFIG_FLASH_SECTOR  FLASH_SECTOR_4


typedef struct __attribute__((packed, aligned(4)))
{
    uint32_t magic;
    uint8_t  active_slot;
    uint8_t  pending_slot;
    uint8_t  boot_attempt;
    uint8_t  image_confirmed;
    uint32_t reserved;

} boot_state_t;


/* LED configuration */

#define LED_GPIO_PORT GPIOA
#define LED_PIN       GPIO_PIN_5


UART_HandleTypeDef huart2;


/* Function prototypes */

void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void boot_confirm(void);


/* Main application */

int main(void)
{
    HAL_Init();

    SystemClock_Config();

    MX_GPIO_Init();


    /*
     * Confirm the application after a successful startup.
     */
    boot_confirm();


    while (1)
    {
        HAL_GPIO_TogglePin(LED_GPIO_PORT, LED_PIN);

        HAL_Delay(500);
    }
}


/* Confirm that the new firmware is running correctly. */

static void boot_confirm(void)
{
    boot_state_t *p =
        (boot_state_t *)CONFIG_FLASH_ADDRESS;


    if (p->magic != BOOT_STATE_MAGIC ||
        p->image_confirmed == 1)
    {
        return;
    }


    boot_state_t bs = *p;

    bs.image_confirmed = 1;
    bs.active_slot = bs.pending_slot;
    bs.pending_slot = 0xFF;
    bs.boot_attempt = 0;


    HAL_FLASH_Unlock();


    FLASH_EraseInitTypeDef erase = {0};
    uint32_t sector_error = 0;


    erase.TypeErase = FLASH_TYPEERASE_SECTORS;
    erase.Sector = CONFIG_FLASH_SECTOR;
    erase.NbSectors = 1;
    erase.VoltageRange = FLASH_VOLTAGE_RANGE_3;


    HAL_FLASHEx_Erase(&erase, &sector_error);


    uint32_t *data = (uint32_t *)&bs;
    uint32_t addr = CONFIG_FLASH_ADDRESS;


    for (uint32_t i = 0;
         i < sizeof(boot_state_t) / 4;
         i++)
    {
        HAL_FLASH_Program(FLASH_TYPEPROGRAM_WORD,
                          addr,
                          data[i]);

        addr += 4;
    }


    HAL_FLASH_Lock();
}


/* Configure PA5 as the LED output. */

static void MX_GPIO_Init(void)
{
    __HAL_RCC_GPIOA_CLK_ENABLE();


    GPIO_InitTypeDef GPIO_InitStruct = {0};


    GPIO_InitStruct.Pin = LED_PIN;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;


    HAL_GPIO_Init(LED_GPIO_PORT, &GPIO_InitStruct);


    HAL_GPIO_WritePin(LED_GPIO_PORT,
                      LED_PIN,
                      GPIO_PIN_RESET);
}


/*
 * Use the clock configuration generated by CubeMX
 * for your STM32 project.
 */

void SystemClock_Config(void)
{
    /* Add CubeMX generated clock configuration here. */
}
